# Generated by Django 3.1.3 on 2020-11-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('option1', models.CharField(default='', max_length=255)),
                ('option2', models.CharField(default='', max_length=255)),
                ('option3', models.CharField(default='', max_length=255)),
                ('option4', models.CharField(default='', max_length=255)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.exam')),
            ],
        ),
    ]
