# Generated by Django 3.1.3 on 2021-03-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210304_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='subject',
        ),
    ]
