# Generated by Django 3.1.3 on 2021-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_result_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
